Code Review for <create-animals-table> | Vet Clinic Database Project
luigirazum/happypaw-vetclinic-db pull request #1
Opened 2023-05-09 00:53 UTC by luigirazum

# Hello Dear Code Reviewers Team 👋,
## I would like to ask for your kindly help to do the 🔍 Code Review 👀 for my project.
### The following requirements 📌 were fulfilled this time:
#### - 🎯 General requirements
- 📌 Make sure that you used the correct Gitflow.
  - ✅ The repo was initialized, then a `dev` branch created from `main`.
  - ✅ The `dev` branch was set up as default.
  - ✅ `create-animals-table` feature branch was created from `dev`.
- 📌 Make sure that you documented your work in a professional way.
  - ✅ A README file with all the information about the project was created.

#### - 🎯 Project requirements
- 📌 Use [https://github.com/microverseinc/curriculum-template-databases](https://github.com/microverseinc/curriculum-template-databases) template to generate your repo.
  - ✅ `microverseinc/curriculum-template-databases` template was used to initialize the project.
- 📌 Create a database named `vet_clinic`.
  - ✅ ![image](https://user-images.githubusercontent.com/67355479/236957520-85c24b3b-f31f-4fef-9fad-48a03721d7d7.png)
- 📌 Create a table named `animals` with the following columns: `id`(integer), `name`(string), `date_of_birth`(date), `escape_attempts`(integer), `neutered`(Boolean), `weight_kg`(decimal).
  - ✅ ![image](https://user-images.githubusercontent.com/67355479/236958580-a37e86ac-76ad-4936-a51d-30ed7bc87cf9.png)
  - ✅ ![image](https://user-images.githubusercontent.com/67355479/236959103-5ff7b02f-b766-4092-99cb-9372ec8f392e.png)
- 📌 Copy the SQL you used in the previous point into the `schema.sql` file in the generated repository.
  - ✅ The SQL used to create the animals table was added to the `schema.sql` file.
- 📌 Insert the following data:
  - 🚩 Animal: His name is Agumon. He was born on Feb 3rd, 2020, and currently weighs 10.23kg. He was neutered and he has never tried to escape.
  - 🚩 Animal: Her name is Gabumon. She was born on Nov 15th, 2018, and currently weighs 8kg. She is neutered and she has tried to escape 2 times.
  - 🚩 Animal: His name is Pikachu. He was born on Jan 7th, 2021, and currently weighs 15.04kg. He was not neutered and he has tried to escape once.
  - 🚩 Animal: Her name is Devimon. She was born on May 12th, 2017, and currently weighs 11kg. She is neutered and she has tried to escape 5 times.
    - ✔ ![image](https://user-images.githubusercontent.com/67355479/236960657-734bb4fc-fa7b-4b4d-8d88-bb5645b96891.png)
- 📌 Copy the SQL you used in the previous point into the `data.sql` file in the generated repository.
  - ✅ The SQL used to add data into `animals` table was added to `data.sql` file.
- 📌 Write queries for the following quests:
  - 🚩 Find all animals whose name ends in "mon".
    - ✔ ![image](https://user-images.githubusercontent.com/67355479/236963614-a28e24e5-53d1-4b4d-9ef4-edda7b456d2b.png)
  - 🚩 List the name of all animals born between 2016 and 2019.
    - ✔ ![image](https://user-images.githubusercontent.com/67355479/236964714-e06526cc-bb89-496f-aa16-904ac428422d.png)
  - 🚩 List the name of all animals that are neutered and have less than 3 escape attempts.
    - ✔ ![image](https://user-images.githubusercontent.com/67355479/236964655-d09f15b6-c589-49f8-8128-91a647d2f9d2.png)
  - 🚩 List the date of birth of all animals named either "Agumon" or "Pikachu".
    - ✔ ![image](https://user-images.githubusercontent.com/67355479/236965203-4efe4bec-eb11-4fcc-9361-49a7eeb66826.png)
  - 🚩 List name and escape attempts of animals that weigh more than 10.5kg
    - ✔ ![image](https://user-images.githubusercontent.com/67355479/236965577-8d4f2aa3-86e0-478b-821d-90d60cff82ef.png)
  - 🚩 Find all animals that are neutered.
    - ✔ ![image](https://user-images.githubusercontent.com/67355479/236965822-0f6d8399-6941-4a6c-a148-79c28ab335d3.png)
  - 🚩 Find all animals not named Gabumon.
    - ✔ ![image](https://user-images.githubusercontent.com/67355479/236966095-6145bae0-e093-44dd-bb16-3f16a2549e4e.png)
  - 🚩 Find all animals with a weight between 10.4kg and 17.3kg (including the animals with the weights that equals precisely 10.4kg or 17.3kg)
    - ✔ ![image](https://user-images.githubusercontent.com/67355479/236966549-29d9d166-cc36-42c7-8569-aca66e7ac661.png)
- 📌 **Take a screenshot of the results of your queries.**
  - ✅ All previous queries have their screenshot.
- 📌 Copy the SQL you used in the previous point into the `queries.sql` file in the generated repository.
  - ✅ The SQL used to perform the above queries was added to `queries.sql` file.
- 📌 Remember to add the screenshot with the results of your queries to your Pull Request description.
  - ✅ All screenshots results for every query was added into this Pull Request.

### I really thank you for your support. 🙏
### Cheers and Happy Reviewing! 👀
### Luis 🙋‍♂️

2023-05-09 03:25 UTC, rloterh requested changes
Hi Luis, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 
🏁 🚦 🌴  🏃 🌳 🏡 🏘️ 🌲 

## Highlights 👍  
🎲  Properly created animals table!
🎲  Added required queries!
🎲 ReadMe looks great!

## Required Changes ♻️
_Kindly check the inline comments under the review._

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 03:25 UTC, rloterh commented on README.md
>  This project is [MIT](./LICENSE) licensed.
- [ ] MIT license link is broken, kindly endeavor to fix it.

2023-05-09 03:46 UTC, luigirazum commented on README.md
>  This project is [MIT](./LICENSE) licensed.
Thanks @rloterh, even though I used the template to create the project, that template doesn't include the LICENCE file, it would be good to be included as the README template is.

I'll make the required changes immediately.

2023-05-09 03:56 UTC, Shedrack-Sunday commented on README.md
>  This project is [MIT](./LICENSE) licensed.
Hello @luigirazum , been in the ruby module, you should be experienced enough to know that your projects should always have a license file to make the READE professional. Kindly take note fo this

2023-05-09 03:58 UTC, Shedrack-Sunday approved these changes
Hi @luigirazum 

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

![image](https://i.pinimg.com/originals/3d/d2/07/3dd207237b39dcacd832f94a35428255.gif)


## Highlights
- Nice Pr setup✔️ 
- Good use of SQL for query ✔️ 

## Optional Suggestions 💡
While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.
Cheers, and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread, and don't forget to tag me so I'll receive the notification.

As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-09 04:02 UTC, merged

2023-05-12 09:32 UTC, rloterh commented on README.md
>  This project is [MIT](./LICENSE) licensed.
> Thanks @rloterh, even though I used the template to create the project, that template doesn't include the LICENCE file, it would be good to be included as the README template is.
> 
> I'll make the required changes immediately.

Hi @luigirazum 
Apparently, creating a license yourself indicates that you're responsibly granting permission yourself, since you're the creator/owner of the project. 

Let's therefore endeavor to generate license for each and every project. 💪